<a href="https://colab.research.google.com/github/kmendesDev/project_titanic/blob/main/ml_titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Projeto Titanic - Machine Learning

## Introdu√ß√£o

üëãüõ≥Ô∏è Ol√°, seja bem-vindo ao Desafio Titanic Kaggle! Esta √© a lend√°ria competi√ß√£o de Machine Learning do Titanic - o melhor e primeiro desafio de ML no Kaggle.

Esse projeto foi desenvolvido em colabora√ß√£o com os Cientistas de Dados:

:iphone: Developers contacts

Kaio Mendes - [![General badge](https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white<SUBJECT>-<STATUS>-<COLOR>.svg)](https://www.linkedin.com/in/kaio-mendes-bba196150)  -  [![General badge](https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white<SUBJECT>-<STATUS>-<COLOR>.svg)](https://github.com/kmendesDev)

Cassio Viana - [![General badge](https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white<SUBJECT>-<STATUS>-<COLOR>.svg)](https://www.linkedin.com/in/cvs1987)  -  [![General badge](https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white<SUBJECT>-<STATUS>-<COLOR>.svg)](https://github.com/cvs2010)


O objetivo desse projeto √© utilizar aprendizado de m√°quina para criar um modelo que preveja quais passageiros sobreviveram ao naufr√°gio do Titanic.

O Desafio: O naufr√°gio do Titanic √© um dos naufr√°gios mais infames da hist√≥ria. Em 15 de abril de 1912, durante sua viagem inaugural, o RMS Titanic, amplamente considerado "inafund√°vel", afundou ap√≥s colidir com um iceberg. Infelizmente, n√£o havia botes salva-vidas suficientes para todos a bordo, resultando na morte de 1502 dos 2224 passageiros e tripulantes.

Embora tenha havido algum elemento de sorte envolvido na sobreviv√™ncia, parece que alguns grupos de pessoas tinham mais probabilidade de sobreviver do que outros.

Neste projeto, iremos desenvolver um modelo preditivo de Machine Learning que responda √† pergunta: "que tipo de pessoas tinham mais probabilidade de sobreviver?" usando dados dos passageiros (como nome, idade, g√™nero, classe socioecon√¥mica, etc).

Quais Dados foram usados?
Dois conjuntos de dados semelhantes que incluem informa√ß√µes dos passageiros, como nome, idade, g√™nero, classe socioecon√¥mica, etc. Um conjunto de dados √© intitulado train.csv e o outro √© intitulado test.csv.

O train.csv cont√©m os detalhes de um subconjunto dos passageiros a bordo (exatamente 891) e, o que √© mais importante, revelar√° se eles sobreviveram ou n√£o, tamb√©m conhecido como "verdade b√°sica". J√° o conjunto de dados test.csv cont√©m informa√ß√µes semelhantes, mas n√£o revela a "verdade b√°sica" para cada passageiro. Sua tarefa √© prever esses resultados.

Usando os padr√µes encontrados nos dados do train.csv, prevemos se os 418 passageiros a bordo (encontrados no test.csv) sobreviveram.

Confira a pasta "data" para explorar ainda mais os conjuntos de dados.

https://www.kaggle.com/competitions/titanic/overview/description

##Importa√ß√£o de bibliotecas

In [ ]:
# Importando bibliotecas para manuseio de dados e visualiza√ß√£o
import pandas as pd  # Para manusear dados tabulares
import seaborn as srn  # Para gr√°ficos estat√≠sticos
import matplotlib.pyplot as plt  # Para cria√ß√£o de gr√°ficos

# Importando bibliotecas para c√°lculos matem√°ticos e estat√≠sticos
import statistics as sts  # Para c√°lculos matem√°ticos
import numpy as np  # Para opera√ß√µes num√©ricas

# Importando bibliotecas para pr√©-processamento de dados
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.pipeline import make_pipeline

# Importando bibliotecas para balanceamento de classes
from imblearn.under_sampling import RandomUnderSampler

# Importando bibliotecas para avalia√ß√£o de modelos
from sklearn.metrics import (
    roc_auc_score,
    accuracy_score,
    f1_score,
    confusion_matrix,
    classification_report,
    recall_score,
    precision_score,
    fbeta_score
)

# Importando bibliotecas para treinamento de modelos
from sklearn.model_selection import (
    train_test_split,
    cross_val_score,
    StratifiedKFold,
    GridSearchCV,
)

# Importando algoritmos de aprendizado de m√°quina
from sklearn.svm import SVC, SVR
from lightgbm import LGBMClassifier
from sklearn.linear_model import SGDClassifier, LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.cluster import KMeans

##Importa√ß√£o dos dados ap√≥s a limpeza e tratamento

In [ ]:
# Baixar arquivos salvos no github
!wget https://github.com/kmendesDev/project_titanic/raw/main/data/training_data_cleaned.csv
!wget https://github.com/kmendesDev/project_titanic/raw/main/data/testing_data_cleaned.csv
dataset_test = pd.read_csv("/content/testing_data_cleaned.csv")
dataset_train = pd.read_csv("/content/training_data_cleaned.csv")

--2023-09-02 14:34:59--  https://github.com/kmendesDev/project_titanic/raw/main/data/training_data_cleaned.csv
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/kmendesDev/project_titanic/main/data/training_data_cleaned.csv [following]
--2023-09-02 14:35:00--  https://raw.githubusercontent.com/kmendesDev/project_titanic/main/data/training_data_cleaned.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 49724 (49K) [text/plain]
Saving to: ‚Äòtraining_data_cleaned.csv.2‚Äô

training_data_clean 100%[===================>]  48.56K  --.-KB/s    in 0.04s

2023-09-02 14:35:00 (1.24 MB/s) - ‚Äòtraining_data_cleaned.csv.2‚Äô saved [49724/49724]

--2023-09-02 14:35:00--  https://github.com/kmendesDev/project_titanic/raw/main/data/testing_data_cleaned.csv
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/kmendesDev/project_titanic/main/data/testing_data_cleaned.csv [following]
--2023-09-02 14:35:01--  https://raw.githubusercontent.com/kmendesDev/project_titanic/main/data/testing_data_cleaned.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 22713 (22K) [text/plain]
Saving to: ‚Äòtesting_data_cleaned.csv.2‚Äô

testing_data_cleane 100%[===================>]  22.18K  --.-KB/s    in 0.005s

2023-09-02 14:35:01 (4.46 MB/s) - ‚Äòtesting_data_cleaned.csv.2‚Äô saved [22713/22713]

In [ ]:
dataset_train

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Ticket_number,Ticket_value_encoded,Ticket_final,Cabin_encoded,Cabin_number,Cabin_combined
0,1,0,3,22.0,1,0,7.2500,0,1,0,0,1,21171,1,121171,0,0,0
1,2,1,1,38.0,1,0,71.2833,1,0,1,0,0,17599,2,217599,3,85,385
2,3,1,3,26.0,0,0,7.9250,1,0,0,0,1,3101282,3,33101282,0,0,0
3,4,1,1,35.0,1,0,53.1000,1,0,0,0,1,113803,4,4113803,3,123,3123
4,5,0,3,35.0,0,0,8.0500,0,1,0,0,1,373450,4,4373450,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,27.0,0,0,13.0000,0,1,0,0,1,211536,4,4211536,0,0,0
887,888,1,1,19.0,0,0,30.0000,1,0,0,0,1,112053,4,4112053,2,42,242
888,889,0,3,29.0,1,2,23.4500,1,0,0,0,1,6607,16,166607,0,0,0
889,890,1,1,26.0,0,0,30.0000,0,1,1,0,0,111369,4,4111369,3,148,3148
890,891,0,3,32.0,0,0,7.7500,0,1,0,1,0,370376,4,4370376,0,0,0

In [ ]:
dataset_train.tail()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Ticket_number,Ticket_value_encoded,Ticket_final,Cabin_encoded,Cabin_number,Cabin_combined
886,887,0,2,27.0,0,0,13.00,0,1,0,0,1,211536,4,4211536,0,0,0
887,888,1,1,19.0,0,0,30.00,1,0,0,0,1,112053,4,4112053,2,42,242
888,889,0,3,29.0,1,2,23.45,1,0,0,0,1,6607,16,166607,0,0,0
889,890,1,1,26.0,0,0,30.00,0,1,1,0,0,111369,4,4111369,3,148,3148
890,891,0,3,32.0,0,0,7.75,0,1,0,1,0,370376,4,4370376,0,0,0

In [ ]:
dataset_train.shape

(891, 18)

In [ ]:
dataset_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PassengerId           891 non-null    int64
 1   Survived              891 non-null    int64
 2   Pclass                891 non-null    int64
 3   Age                   891 non-null    float64
 4   SibSp                 891 non-null    int64
 5   Parch                 891 non-null    int64
 6   Fare                  891 non-null    float64
 7   Sex_female            891 non-null    int64
 8   Sex_male              891 non-null    int64
 9   Embarked_C            891 non-null    int64
 10  Embarked_Q            891 non-null    int64
 11  Embarked_S            891 non-null    int64
 12  Ticket_number         891 non-null    int64
 13  Ticket_value_encoded  891 non-null    int64
 14  Ticket_final          891 non-null    int64
 15  Cabin_encoded         891 non-null    int64
 16  Cabin_number          891 non-null    int64
 17  Cabin_combined        891 non-null    int64
dtypes: float64(2), int64(16)
memory usage: 125.4 KB

In [ ]:
dataset_train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Ticket_number,Ticket_value_encoded,Ticket_final,Cabin_encoded,Cabin_number,Cabin_combined
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,8.910000e+02,891.000000,8.910000e+02,891.000000,8.910000e+02,8.910000e+02
mean,446.000000,0.383838,2.308642,29.560236,0.523008,0.381594,32.204208,0.352413,0.647587,0.188552,0.086420,0.725028,2.552204e+05,6.437710,6.200213e+06,8.343434,1.315773e+05,5.008941e+08
std,257.353842,0.486592,0.836071,13.005010,1.102743,0.806057,49.693429,0.477990,0.477990,0.391372,0.281141,0.446751,5.694927e+05,7.335101,2.863388e+07,108.018688,2.727308e+06,1.052412e+10
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,1.000000,1.900000e+02,0.000000,0.000000e+00,0.000000e+00
25%,223.500000,0.000000,2.000000,22.000000,0.000000,0.000000,7.910400,0.000000,0.000000,0.000000,0.000000,0.000000,1.351850e+04,4.000000,2.177580e+05,0.000000,0.000000e+00,0.000000e+00
50%,446.000000,0.000000,3.000000,29.000000,0.000000,0.000000,14.454200,0.000000,1.000000,0.000000,0.000000,1.000000,1.108130e+05,4.000000,4.111320e+06,0.000000,0.000000e+00,0.000000e+00
75%,668.500000,1.000000,3.000000,35.000000,1.000000,0.000000,31.000000,1.000000,1.000000,0.000000,0.000000,1.000000,3.470735e+05,4.000000,4.347076e+06,0.000000,0.000000e+00,0.000000e+00
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,1.000000,1.000000,1.000000,1.000000,1.000000,3.101317e+06,44.000000,4.231013e+08,2222.000000,5.759637e+07,2.222576e+11

In [ ]:
dataset_test

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Ticket_number,Ticket_value_encoded,Ticket_final,Cabin_encoded,Cabin_number,Cabin_combined
0,892,3,34.5,0,0,7.8292,0,1,0,1,0,330911,0,330911,0,0,0
1,893,3,47.0,1,0,7.0000,1,0,0,0,1,363272,0,363272,0,0,0
2,894,2,62.0,0,0,9.6875,0,1,0,1,0,240276,0,240276,0,0,0
3,895,3,27.0,0,0,8.6625,0,1,0,0,1,315154,0,315154,0,0,0
4,896,3,22.0,1,1,12.2875,1,0,0,0,1,3101298,0,3101298,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,30.0,0,0,8.0500,0,1,0,0,1,3236,25,253236,0,0,0
414,1306,1,39.0,0,0,108.9000,1,0,1,0,0,17758,2,217758,3,105,3105
415,1307,3,38.5,0,0,7.2500,0,1,0,0,1,3101262,22,223101262,0,0,0
416,1308,3,30.0,0,0,8.0500,0,1,0,0,1,359309,0,359309,0,0,0
417,1309,3,30.0,1,1,22.3583,0,1,1,0,0,2668,0,2668,0,0,0

In [ ]:
dataset_test.tail()

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Ticket_number,Ticket_value_encoded,Ticket_final,Cabin_encoded,Cabin_number,Cabin_combined
413,1305,3,30.0,0,0,8.0500,0,1,0,0,1,3236,25,253236,0,0,0
414,1306,1,39.0,0,0,108.9000,1,0,1,0,0,17758,2,217758,3,105,3105
415,1307,3,38.5,0,0,7.2500,0,1,0,0,1,3101262,22,223101262,0,0,0
416,1308,3,30.0,0,0,8.0500,0,1,0,0,1,359309,0,359309,0,0,0
417,1309,3,30.0,1,1,22.3583,0,1,1,0,0,2668,0,2668,0,0,0

In [ ]:
dataset_test.shape

(418, 17)

In [ ]:
dataset_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PassengerId           418 non-null    int64
 1   Pclass                418 non-null    int64
 2   Age                   418 non-null    float64
 3   SibSp                 418 non-null    int64
 4   Parch                 418 non-null    int64
 5   Fare                  418 non-null    float64
 6   Sex_female            418 non-null    int64
 7   Sex_male              418 non-null    int64
 8   Embarked_C            418 non-null    int64
 9   Embarked_Q            418 non-null    int64
 10  Embarked_S            418 non-null    int64
 11  Ticket_number         418 non-null    int64
 12  Ticket_value_encoded  418 non-null    int64
 13  Ticket_final          418 non-null    int64
 14  Cabin_encoded         418 non-null    int64
 15  Cabin_number          418 non-null    int64
 16  Cabin_combined        418 non-null    int64
dtypes: float64(2), int64(15)
memory usage: 55.6 KB

In [ ]:
dataset_test.describe()

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Ticket_number,Ticket_value_encoded,Ticket_final,Cabin_encoded,Cabin_number,Cabin_combined
count,418.000000,418.000000,418.000000,418.000000,418.000000,418.000000,418.000000,418.000000,418.000000,418.000000,418.000000,4.180000e+02,418.000000,4.180000e+02,418.000000,4.180000e+02,4.180000e+02
mean,1100.500000,2.265550,30.216507,0.447368,0.392344,35.625688,0.363636,0.636364,0.244019,0.110048,0.645933,2.384720e+05,3.921053,5.735537e+06,20.260766,4.170550e+05,1.597816e+09
std,120.810458,0.841838,12.635016,0.896760,0.981429,55.840509,0.481622,0.481622,0.430019,0.313324,0.478803,5.537201e+05,9.143985,3.681155e+07,189.561444,4.867543e+06,1.878367e+10
min,892.000000,1.000000,0.170000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00
25%,996.250000,1.000000,23.000000,0.000000,0.000000,7.895800,0.000000,0.000000,0.000000,0.000000,0.000000,1.309650e+04,0.000000,2.815475e+04,0.000000,0.000000e+00,0.000000e+00
50%,1100.500000,3.000000,30.000000,0.000000,0.000000,14.454200,0.000000,1.000000,0.000000,0.000000,1.000000,3.384400e+04,0.000000,2.238600e+05,0.000000,0.000000e+00,0.000000e+00
75%,1204.750000,3.000000,35.750000,1.000000,0.000000,31.500000,1.000000,1.000000,0.000000,0.000000,1.000000,3.431312e+05,2.000000,3.492342e+05,0.000000,0.000000e+00,0.000000e+00
max,1309.000000,3.000000,76.000000,8.000000,9.000000,512.329200,1.000000,1.000000,1.000000,1.000000,1.000000,3.101315e+06,43.000000,4.231013e+08,2222.000000,5.759637e+07,2.222576e+11

# Modelo de Machine Learning

## Checando os dados antes de instanciar o modelo
- Verificando valores NaN
- Verificando valores num√©ricos
- Verificando se ainda h√° dados faltantes
- Verificando se ainda h√° dados categ√≥ricos
- Verificando nomes de colunas corretos nos datasets de treinamento e teste

In [ ]:
dataset_train_ml = dataset_train
dataset_test_ml = dataset_test

In [ ]:
dataset_train_ml

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Ticket_number,Ticket_value_encoded,Ticket_final,Cabin_encoded,Cabin_number,Cabin_combined
0,1,0,3,22.0,1,0,7.2500,0,1,0,0,1,21171,1,121171,0,0,0
1,2,1,1,38.0,1,0,71.2833,1,0,1,0,0,17599,2,217599,3,85,385
2,3,1,3,26.0,0,0,7.9250,1,0,0,0,1,3101282,3,33101282,0,0,0
3,4,1,1,35.0,1,0,53.1000,1,0,0,0,1,113803,4,4113803,3,123,3123
4,5,0,3,35.0,0,0,8.0500,0,1,0,0,1,373450,4,4373450,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,27.0,0,0,13.0000,0,1,0,0,1,211536,4,4211536,0,0,0
887,888,1,1,19.0,0,0,30.0000,1,0,0,0,1,112053,4,4112053,2,42,242
888,889,0,3,29.0,1,2,23.4500,1,0,0,0,1,6607,16,166607,0,0,0
889,890,1,1,26.0,0,0,30.0000,0,1,1,0,0,111369,4,4111369,3,148,3148
890,891,0,3,32.0,0,0,7.7500,0,1,0,1,0,370376,4,4370376,0,0,0

In [ ]:
dataset_test_ml

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Ticket_number,Ticket_value_encoded,Ticket_final,Cabin_encoded,Cabin_number,Cabin_combined
0,892,3,34.5,0,0,7.8292,0,1,0,1,0,330911,0,330911,0,0,0
1,893,3,47.0,1,0,7.0000,1,0,0,0,1,363272,0,363272,0,0,0
2,894,2,62.0,0,0,9.6875,0,1,0,1,0,240276,0,240276,0,0,0
3,895,3,27.0,0,0,8.6625,0,1,0,0,1,315154,0,315154,0,0,0
4,896,3,22.0,1,1,12.2875,1,0,0,0,1,3101298,0,3101298,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,30.0,0,0,8.0500,0,1,0,0,1,3236,25,253236,0,0,0
414,1306,1,39.0,0,0,108.9000,1,0,1,0,0,17758,2,217758,3,105,3105
415,1307,3,38.5,0,0,7.2500,0,1,0,0,1,3101262,22,223101262,0,0,0
416,1308,3,30.0,0,0,8.0500,0,1,0,0,1,359309,0,359309,0,0,0
417,1309,3,30.0,1,1,22.3583,0,1,1,0,0,2668,0,2668,0,0,0

In [ ]:
dataset_test_ml.shape

(418, 17)

In [ ]:
dataset_train_ml.shape

(891, 18)

In [ ]:
dataset_test_ml.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PassengerId           418 non-null    int64
 1   Pclass                418 non-null    int64
 2   Age                   418 non-null    float64
 3   SibSp                 418 non-null    int64
 4   Parch                 418 non-null    int64
 5   Fare                  418 non-null    float64
 6   Sex_female            418 non-null    int64
 7   Sex_male              418 non-null    int64
 8   Embarked_C            418 non-null    int64
 9   Embarked_Q            418 non-null    int64
 10  Embarked_S            418 non-null    int64
 11  Ticket_number         418 non-null    int64
 12  Ticket_value_encoded  418 non-null    int64
 13  Ticket_final          418 non-null    int64
 14  Cabin_encoded         418 non-null    int64
 15  Cabin_number          418 non-null    int64
 16  Cabin_combined        418 non-null    int64
dtypes: float64(2), int64(15)
memory usage: 55.6 KB

In [ ]:
dataset_train_ml.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PassengerId           891 non-null    int64
 1   Survived              891 non-null    int64
 2   Pclass                891 non-null    int64
 3   Age                   891 non-null    float64
 4   SibSp                 891 non-null    int64
 5   Parch                 891 non-null    int64
 6   Fare                  891 non-null    float64
 7   Sex_female            891 non-null    int64
 8   Sex_male              891 non-null    int64
 9   Embarked_C            891 non-null    int64
 10  Embarked_Q            891 non-null    int64
 11  Embarked_S            891 non-null    int64
 12  Ticket_number         891 non-null    int64
 13  Ticket_value_encoded  891 non-null    int64
 14  Ticket_final          891 non-null    int64
 15  Cabin_encoded         891 non-null    int64
 16  Cabin_number          891 non-null    int64
 17  Cabin_combined        891 non-null    int64
dtypes: float64(2), int64(16)
memory usage: 125.4 KB

In [ ]:
# Verificando valores NaN no dataset_training_ml
dataset_train_ml.isnull().sum()

PassengerId             0
Survived                0
Pclass                  0
Age                     0
SibSp                   0
Parch                   0
Fare                    0
Sex_female              0
Sex_male                0
Embarked_C              0
Embarked_Q              0
Embarked_S              0
Ticket_number           0
Ticket_value_encoded    0
Ticket_final            0
Cabin_encoded           0
Cabin_number            0
Cabin_combined          0
dtype: int64

In [ ]:
# Verificando valores NaN no dataset_training_ml
dataset_test_ml.isnull().sum()

PassengerId             0
Pclass                  0
Age                     0
SibSp                   0
Parch                   0
Fare                    0
Sex_female              0
Sex_male                0
Embarked_C              0
Embarked_Q              0
Embarked_S              0
Ticket_number           0
Ticket_value_encoded    0
Ticket_final            0
Cabin_encoded           0
Cabin_number            0
Cabin_combined          0
dtype: int64

In [ ]:
# Checando os nomes das colunas nos datasets de treino e teste
print('Colunas do dataset_train_ml: ', dataset_train_ml.columns)
print('/n')
print('Colunas do dataset_test_ml: ', dataset_test_ml.columns)

Colunas do dataset_train_ml:  Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare',
       'Sex_female', 'Sex_male', 'Embarked_C', 'Embarked_Q', 'Embarked_S',
       'Ticket_number', 'Ticket_value_encoded', 'Ticket_final',
       'Cabin_encoded', 'Cabin_number', 'Cabin_combined'],
      dtype='object')
/n
Colunas do dataset_test_ml:  Index(['PassengerId', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_female',
       'Sex_male', 'Embarked_C', 'Embarked_Q', 'Embarked_S', 'Ticket_number',
       'Ticket_value_encoded', 'Ticket_final', 'Cabin_encoded', 'Cabin_number',
       'Cabin_combined'],
      dtype='object')

Tudo ok
- Mesma quantidade de colunas (training tem uma coluna a mais 'Survived')
- Mesmas etiquetas nas colunas dos datasets de treino e teste
- Todos os valores num√©ricos com o mesmo tipo em cada coluna
- N√£o h√° valores faltantes

## Criando o prot√≥tipo do modelo

### Definindo qual modelo de machine learning utilizar

Breve explica√ß√£o a cerca de cada modelo:

1. **RandomForestClassifier (rf)**:
   - Tipo: Ensemble de √°rvores de decis√£o.
   - Funcionamento: Cria um conjunto de √°rvores de decis√£o e combina suas previs√µes para obter uma decis√£o final.
   - Uso: Classifica√ß√£o e tamb√©m pode ser usado para tarefas de regress√£o.

2. **DecisionTreeClassifier (dt)**:
   - Tipo: √Årvore de decis√£o.
   - Funcionamento: Constr√≥i uma √°rvore de decis√£o bin√°ria que divide o espa√ßo de caracter√≠sticas em regi√µes para tomar decis√µes de classifica√ß√£o.
   - Uso: Classifica√ß√£o.

3. **SGDClassifier (sgdc)**:
   - Tipo: Gradiente Descendente Estoc√°stico (SGD) Classifier.
   - Funcionamento: Usa o SGD para treinar modelos lineares, incluindo SVMs lineares e regress√£o log√≠stica.
   - Uso: Classifica√ß√£o.

4. **SVC (svc)**:
   - Tipo: Support Vector Classifier (SVC).
   - Funcionamento: Usa vetores de suporte para encontrar um hiperplano que melhor separa as classes em espa√ßos de alta dimens√£o.
   - Uso: Classifica√ß√£o.

5. **LogisticRegression (lr)**:
   - Tipo: Regress√£o Log√≠stica.
   - Funcionamento: Modela a probabilidade de uma classe usando uma fun√ß√£o log√≠stica.
   - Uso: Classifica√ß√£o.

6. **XGBClassifier (xgb)**:
   - Tipo: Gradient Boosting Classifier.
   - Funcionamento: Usa o m√©todo de impulso para melhorar o desempenho dos modelos fracos, geralmente √°rvores de decis√£o.
   - Uso: Classifica√ß√£o.

7. **LGBMClassifier (lgbm)**:
   - Tipo: Gradient Boosting Classifier, com otimiza√ß√£o para efici√™ncia.
   - Funcionamento: Semelhante ao XGBoost, mas otimizado para velocidade e efici√™ncia computacional.
   - Uso: Classifica√ß√£o.

8. **GaussianNB (nb)**:
   - Tipo: Naive Bayes.
   - Funcionamento: Baseado no teorema de Bayes, assume independ√™ncia condicional entre as caracter√≠sticas.
   - Uso: Classifica√ß√£o, especialmente quando as premissas ing√™nuas de independ√™ncia s√£o atendidas.

Cada um desses modelos √© adequado para diferentes tipos de problemas de classifica√ß√£o, e a escolha depende da natureza dos dados e dos requisitos de desempenho.

Os modelos K-means e SVR (support vector regression) n√£o s√£o adequados para problemas de classifica√ß√£o.

  9. **K-Means:**

  Tipo de Problema:

  O K-Means √© usado para clusteriza√ß√£o, onde o objetivo √© agrupar dados sem r√≥tulos em grupos com base em similaridade.
  
  Supervis√£o:

    - Os modelos de classifica√ß√£o requerem dados de treinamento rotulados para aprender a fazer previs√µes.
    - O K-Means n√£o requer r√≥tulos; ele encontra agrupamentos com base apenas na similaridade entre os dados.
    Sa√≠da:

  Os modelos de classifica√ß√£o produzem uma classe como sa√≠da (por exemplo, "spam" ou "n√£o spam").
  O K-Means produz r√≥tulos de clusters para cada observa√ß√£o.

  10. **SVR (Support Vector Regression):**

  Tipo de Problema:

  O SVR √© usado para regress√£o, onde o objetivo √© prever um valor cont√≠nuo (por exemplo, prever o pre√ßo de uma casa).
  Sa√≠da:

    - Os modelos de classifica√ß√£o produzem classes categ√≥ricas como sa√≠da (por exemplo, "sim" ou "n√£o").
    - O SVR produz valores num√©ricos como sa√≠da, que representam uma estimativa cont√≠nua.


Os modelos de classifica√ß√£o usam algoritmos que se concentram na separa√ß√£o de classes, como √°rvores de decis√£o, regress√£o log√≠stica, entre outros.
O SVR utiliza a t√©cnica de M√°quinas de Vetores de Suporte para realizar a regress√£o, encontrando um hiperplano que melhor se ajusta aos dados de treinamento. Em resumo, a principal diferen√ßa est√° no tipo de problema que eles resolvem e na natureza de suas sa√≠das. Os outros modelos s√£o amplamente usados para classifica√ß√£o, enquanto o K-Means √© usado para clusteriza√ß√£o e o SVR para regress√£o.

In [ ]:
def val_model(X, y, clf):
    """
    Cross Validation Function.

    # Arguments
        X: DataFrame, independent variables.
        y: Series, vector, target variable.
        clf: Scikit-learn Classifier.
        quiet: bool, indicating whether the function should print the results.

    # Returns
        tuple, containing cross-validation average accuracy, ROC AUC, Recall, Precision, F1-Score
    """
    # Transforming X and y to numpy arrays
    X = np.array(X)
    y = np.array(y)
    # Creating a pipeline with StandardScaler and clf (classifier model)
    pipeline = make_pipeline(StandardScaler(), clf)
    # Performing cross validation and scoring metrics
    scores = cross_val_score(pipeline, X, y, scoring='accuracy')
    roc_auc_scores = cross_val_score(pipeline, X, y, scoring='roc_auc')
    recall_scores = cross_val_score(pipeline, X, y, scoring='recall')
    precision_scores = cross_val_score(pipeline, X, y, scoring='precision')
    f1_scores = cross_val_score(pipeline, X, y, scoring='f1')
    # Returning results
    return scores.mean(), roc_auc_scores.mean(), recall_scores.mean(), precision_scores.mean(), f1_scores.mean()

# Instantiating the variables X and y
X = dataset_train_ml.drop(columns=['Survived'])
y = dataset_train_ml['Survived']

# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardizing the data (Centering: The mean (average) of the data and Scaling: The standard deviation)
scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)

# X_train columns names
X_train = pd.DataFrame(X_train, columns=X.columns)

# Undersampling (data preprocessing technique used to balance class distributions in imbalanced datasets)
rus = RandomUnderSampler(random_state=42)
X_train_rus, y_train_rus = rus.fit_resample(X_train, y_train)

# Instantiating the models
rf = RandomForestClassifier(random_state=42)
dt = DecisionTreeClassifier(random_state=42)
sgdc = SGDClassifier(random_state=42)
svc = SVC(random_state=42)
lr = LogisticRegression(random_state=42)
xgb = XGBClassifier(random_state=42)
lgbm = LGBMClassifier(random_state=42, verbose=-1)
nb = GaussianNB()

# Creating the lists
model = []
accuracy = []
roc_auc = []
recall = []
precision = []
f1 = []
confusion_matrices = []

# Fitting the models
rf_fit = rf.fit(X_train_rus, y_train_rus)
dt_fit = dt.fit(X_train_rus, y_train_rus)
sgdc_fit = sgdc.fit(X_train_rus, y_train_rus)
svc_fit = svc.fit(X_train_rus, y_train_rus)
lr_fit = lr.fit(X_train_rus, y_train_rus)
xgb_fit = xgb.fit(X_train_rus, y_train_rus)
lgbm_fit = lgbm.fit(X_train_rus, y_train_rus)
nb_fit = nb.fit(X_train_rus, y_train_rus)

# Evaluating results (accuracy, roc_auc, recall, precision, f1, confusion matrix)
# This loop iterates through each of the listed models, collects the name of the classifier's class,
# and calculates performance metrics using the val_model function.
for clf in (rf, dt, sgdc, svc, lr, xgb, lgbm, nb):
    model.append(clf.__class__.__name__)
    acc, roc_auc_score, recall_score, precision_score_value, f1_score_value = val_model(X_train_rus, y_train_rus, clf)
    # Calculating confusion matrix
    y_pred = clf.predict(X_test)
    confusion_matrix_value = confusion_matrix(y_test, y_pred)
    # Appending the scores of each model
    accuracy.append(acc)
    roc_auc.append(roc_auc_score)
    recall.append(recall_score)
    precision.append(precision_score_value)
    f1.append(f1_score_value)
    confusion_matrices.append(confusion_matrix_value)

# Creating a DataFrame to store results
results_df = pd.DataFrame({
    'Model': model,
    'Accuracy': accuracy,
    'ROC AUC': roc_auc,
    'Recall': recall,
    'Precision': precision,
    'F1-Score': f1,
    'Confusion Matrix': confusion_matrices
})

# Calculating the mean of metrics
results_df['Mean Score'] = results_df[['Accuracy', 'ROC AUC', 'Recall', 'Precision', 'F1-Score']].mean(axis=1)

# Starting the index from 1
results_df.index = results_df.index + 1

# Showing the results
results_df

,Model,Accuracy,ROC AUC,Recall,Precision,F1-Score,Confusion Matrix,Mean Score
1,RandomForestClassifier,0.783610,0.850151,0.746331,0.808187,0.775789,"[[7, 98], [8, 66]]",0.792814
2,DecisionTreeClassifier,0.699567,0.699476,0.686443,0.709494,0.696068,"[[105, 0], [74, 0]]",0.698210
3,SGDClassifier,0.705227,0.742181,0.698043,0.709487,0.697864,"[[105, 0], [73, 1]]",0.710560
4,SVC,0.785445,0.839810,0.724039,0.827842,0.770538,"[[105, 0], [74, 0]]",0.789535
5,LogisticRegression,0.764849,0.840512,0.753529,0.770934,0.761292,"[[105, 0], [73, 1]]",0.778223
6,XGBClassifier,0.763067,0.845762,0.753739,0.768507,0.760370,"[[105, 0], [71, 3]]",0.778289
7,LGBMClassifier,0.791121,0.859413,0.787491,0.796234,0.791120,"[[88, 17], [22, 52]]",0.805076
8,GaussianNB,0.518640,0.784287,0.067086,0.726667,0.121017,"[[95, 10], [45, 29]]",0.443539

**M√©tricas de Desempenho de Modelos de Machine Learning:**

**1. Accuracy (Acur√°cia):**
   - √â a m√©trica mais comum para avaliar o desempenho de um modelo.
   - Calcula a propor√ß√£o de previs√µes corretas em rela√ß√£o ao total de previs√µes.
   - A f√≥rmula √©: `(N√∫mero de previs√µes corretas) / (N√∫mero total de previs√µes)`.

**2. ROC AUC (√Årea sob a Curva ROC):**
   - Avalia a capacidade de classifica√ß√£o de um modelo de classifica√ß√£o bin√°ria.
   - A Curva ROC (Receiver Operating Characteristic) mostra a taxa de verdadeiros positivos em rela√ß√£o √† taxa de falsos positivos em diferentes limiares de classifica√ß√£o.
   - O ROC AUC √© a √°rea sob essa curva. Quanto maior, melhor.
   - √â √∫til quando os dados est√£o desequilibrados.

**3. Recall (Revoca√ß√£o):**
   - Tamb√©m conhecido como Sensibilidade ou Taxa de Verdadeiros Positivos.
   - Mede a propor√ß√£o de verdadeiros positivos (inst√¢ncias relevantes corretamente previstas) em rela√ß√£o ao total de inst√¢ncias relevantes no conjunto de dados.
   - √â importante quando o custo de falsos negativos √© alto, como em diagn√≥sticos m√©dicos.

**4. Precision (Precis√£o):**
   - Tamb√©m conhecida como Valor Preditivo Positivo.
   - Mede a propor√ß√£o de verdadeiros positivos em rela√ß√£o ao total de previs√µes positivas feitas pelo modelo.
   - √â importante quando o custo de falsos positivos √© alto, como em sistemas de detec√ß√£o de spam.

**5. F1-Score:**
   - √â a m√©dia harm√¥nica entre Recall e Precision.
   - Oferece um equil√≠brio entre Recall e Precision.
   - √â √∫til quando voc√™ deseja levar em considera√ß√£o tanto os falsos positivos quanto os falsos negativos.
   - A f√≥rmula √©: `2 * (Precision * Recall) / (Precision + Recall)`.

**6. Confusion Matrix (Matriz de Confus√£o):**
   - √â uma tabela que descreve o desempenho de um modelo de classifica√ß√£o em um conjunto de dados de teste.
   - Possui quatro elementos:
     - Verdadeiros Positivos (TP): Inst√¢ncias positivas corretamente classificadas.
     - Verdadeiros Negativos (TN): Inst√¢ncias negativas corretamente classificadas.
     - Falsos Positivos (FP): Inst√¢ncias negativas erroneamente classificadas como positivas.
     - Falsos Negativos (FN): Inst√¢ncias positivas erroneamente classificadas como negativas.
   - √â uma ferramenta poderosa para entender onde o modelo est√° errando e acertando.

Essas m√©tricas s√£o usadas para avaliar o desempenho de modelos de machine learning e ajudam a tomar decis√µes sobre a escolha do modelo, ajustes de hiperpar√¢metros e otimiza√ß√£o do desempenho. A escolha da m√©trica certa depende do problema e das consequ√™ncias de falsos positivos e falsos negativos.

### Modelo de Random Forest

In [ ]:
# Resetando o dataset_test_ml
dataset_test_ml = dataset_test

In [ ]:
X = dataset_train_ml.drop(columns=['Survived'])
y = dataset_train_ml['Survived']

# Dividindo o conjunto de dados em treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Criando o modelo de Random Forest
random_forest = RandomForestClassifier(random_state=42)

# Treinando o modelo
random_forest.fit(X_train, y_train)

# Fazendo previs√µes no conjunto de teste
y_pred = random_forest.predict(X_test)

# Calculando a acur√°cia do modelo
accuracy = accuracy_score(y_test, y_pred)
print(f'Acur√°cia do modelo: {accuracy:.5f}')

Acur√°cia do modelo: 0.82123

In [ ]:
# Resetando o nome da vari√°vel classification_report
from sklearn.metrics import classification_report # N√£o entendi porque est√° acontecendo isso??? Se retirar essa linha d√° erro
class_report = classification_report(y_test, y_pred)
print("Relat√≥rio de Classifica√ß√£o:")
print(class_report)
# Converter o relat√≥rio em um DataFrame
classification_report = pd.DataFrame(classification_report(y_test, y_pred, output_dict=True)).transpose()
# Calcular a m√©dia das m√©tricas
mean_metrics = classification_report.mean()
# Excluir a coluna "support" das m√©dias, se necess√°rio
mean_metrics = mean_metrics.drop("support")
# Calcular a m√©dia entre as m√©tricas
mean_average = mean_metrics.mean()
# Exibir a m√©dia entre as m√©tricas
print(f'M√©dia das M√©tricas {mean_average:.5f}')
# Exibindo o F2-score no conjunto de teste
# Calculando o F2-score no conjunto de teste
f2_test_score = fbeta_score(y_test, y_pred, beta=2)
print(f'F2-score no conjunto de teste: {f2_test_score:.5f}')
# Calculando a acur√°cia do modelo
accuracy = accuracy_score(y_test, y_pred)
print(f'Acur√°cia: {accuracy:.5f} \n')

Relat√≥rio de Classifica√ß√£o:
              precision    recall  f1-score   support

           0       0.82      0.90      0.85       105
           1       0.83      0.72      0.77        74

    accuracy                           0.82       179
   macro avg       0.82      0.81      0.81       179
weighted avg       0.82      0.82      0.82       179

M√©dia das M√©tricas 0.81633
F2-score no conjunto de teste: 0.73611
Acur√°cia: 0.82123

In [ ]:
# Prevendo a sobreviv√™ncia para o conjunto de teste

# Excluindo a coluna 'Survived'
dataset_test_ml = dataset_test_ml.drop(columns=['Survived'])

# Separando a caracter√≠stica "Survived"
dataset_test_ml['Survived'] = random_forest.predict(dataset_test_ml)

# Movendo a coluna "Survived" para a segunda posi√ß√£o
dataset_test_ml = dataset_test_ml[['PassengerId', 'Survived']].copy()

In [ ]:
dataset_test_ml

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [ ]:
# Contagem de sobreviventes
dataset_test_ml['Survived'].value_counts()

0    278
1    140
Name: Survived, dtype: int64

In [ ]:
# Selecionando apenas as colunas PassengerId e Survived do dataset_test_ml
dataset_test_submission = dataset_test_ml[['PassengerId', 'Survived']].copy()

# Transformando a coluna "Survived" em valores num√©ricos inteiros usando .loc[]
dataset_test_submission['Survived'] = dataset_test_submission['Survived'].astype(int)

# Resetando o √≠ndice
dataset_test_submission.reset_index(drop=True, inplace=True)
dataset_test_submission

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [ ]:
# Verificando o shape do dataset_test_submission antes de salvar o arquivo .csv
dataset_test_submission.shape

(418, 2)

In [ ]:
# Salvando o dataset_test_submission em um arquivo .csv
dataset_test_submission.to_csv('dataset_test_submission.csv', index=False)

Prevendo a sobreviv√™ncia de cada passageiro em taxa (%)

In [ ]:
# Carregue seus dados e prepare X e y
X = dataset_train_ml.drop(columns=['Survived'])
y = dataset_train_ml['Survived']

# Divida o conjunto de dados em treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Crie o modelo XGBoost
random_forest = RandomForestClassifier(random_state=42)

# Treine o modelo
random_forest.fit(X_train, y_train)

# Fa√ßa previs√µes de probabilidades no conjunto de teste
y_probabilities = random_forest.predict_proba(X_test)

# Obtenha as probabilidades de sobreviv√™ncia (classe 1)
survival_probabilities = y_probabilities[:, 1]

# Arredonde as probabilidades de sobreviv√™ncia para duas casas decimais
survival_probabilities_rounded = [round(prob, 3) for prob in survival_probabilities]

# Crie um DataFrame com as probabilidades arredondadas e a coluna 'Sobreviveu' baseada em y_pred
result_df = pd.DataFrame({'Taxa de Sobreviv√™ncia': survival_probabilities_rounded,
                          'Sobreviveu': y_pred})

# Exiba o DataFrame resultante
result_df

     Taxa de Sobreviv√™ncia  Sobreviveu
0                     0.35           0
1                     0.06           0
2                     0.08           0
3                     0.97           1
4                     0.35           0
..                     ...         ...
174                   0.41           0
175                   0.09           0
176                   0.22           0
177                   0.88           1
178                   0.56           1

[179 rows x 2 columns]